-- MonOPCO Drop All Tables
-- Date: 2025-11-26

DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS emails CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS dossiers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
